name: Build Cross-Platform Releases

on:
  push:
    tags:
      - 'v*'   # 只有打 tag 时触发，例如 v1.0.0
  workflow_dispatch:

jobs:
  # --- Windows 构建 ---
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt nuitka

      - name: Build with Nuitka
        run: nuitka --onefile --windows-console-mode=disable --enable-plugin=tk-inter --include-package-data=ttkbootstrap --include-data-files=english.txt=./english.txt --output-filename=bip39_recovery.exe bip39_recovery.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: bip39-recovery-windows
          path: bip39_recovery.exe

  # --- Linux (Tails) 构建 ---
  build-tails:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the builder image
        run: docker build -t bip39-builder .

      - name: Run Nuitka inside Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/app bip39-builder \
            python3 -m nuitka --onefile \
              --enable-plugin=tk-inter \
              --include-package-data=ttkbootstrap \
              --include-data-files=english.txt=./english.txt \
              --output-filename=bip39_recovery.bin \
              bip39_recovery.py

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: bip39-recovery-tails
          path: bip39_recovery.bin

  # --- 创建 Release ---
  create-release:
    needs: [build-windows, build-tails]
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: bip39-recovery-windows

      - name: Download Tails artifact
        uses: actions/download-artifact@v4
        with:
          name: bip39-recovery-tails

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            bip39-recovery-windows/bip39_recovery.exe
            bip39-recovery-tails/bip39_recovery.bin
