name: Build Cross-Platform Releases

on:
  push:
    tags:
      - "v*" # 当一个 v 开头的 tag (例如 v1.0, v1.2.3) 被推送到仓库时触发
  workflow_dispatch: # 同时也允许在 Actions 页面手动触发

jobs:
  # ------------------- Windows 构建 -------------------
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt nuitka

      - name: Build with Nuitka
        run: |
          python -m nuitka --onefile `
            --yes `
            --windows-console-mode=disable `
            --enable-plugin=pyside6 `
            --include-data-file=english.txt=english.txt `
            --output-filename=bip39_recovery-windows.exe `
            bip39_recovery.py
        env:
          # 这个环境变量可以保留，但 --yes 参数更具决定性
          NUITKA_ALLOW_DEPENDS_DOWNLOAD: 1

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: bip39-recovery-windows
          path: bip39_recovery-windows.exe

  # ------------------- Linux 构建 (使用 Docker) -------------------
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image for our builder
        run: docker build -t bip39-builder .

      - name: Run Nuitka inside Docker as current user
        # 核心修改：添加 --user $(id -u):$(id -g)
        # 这会以当前宿主机用户（runner）的身份在容器内执行命令
        # 从而保证创建的文件的所有权是正确的
        run: |
          docker run --rm --user $(id -u):$(id -g) -v ${{ github.workspace }}:/app bip39-builder python3 -m nuitka \
            --onefile \
            --enable-plugin=pyside6 \
            --include-data-file=english.txt=english.txt \
            --output-filename=bip39_recovery-linux \
            bip39_recovery.py

      - name: Set executable permissions
        # 现在，因为文件的所有者是 runner，这个命令将能成功执行
        run: chmod +x bip39_recovery-linux

      - name: Upload Linux executable
        uses: actions/upload-artifact@v4
        with:
          name: bip39-recovery-linux
          path: bip39_recovery-linux

  # ------------------- macOS 构建 -------------------
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt nuitka

      - name: Build with Nuitka
        # 在 bash shell 中，行继续符是反斜杠 (\)
        run: |
          python -m nuitka --onefile \
            --macos-create-app-bundle \
            --enable-plugin=pyside6 \
            --include-data-file=english.txt=english.txt \
            --output-filename=bip39_recovery \
            bip39_recovery.py

      - name: Create Zip of .app bundle
        run: ditto -c -k --sequesterRsrc --keepParent bip39_recovery.app bip39_recovery-macos.zip

      - name: Upload macOS executable zip
        uses: actions/upload-artifact@v4
        with:
          name: bip39-recovery-macos
          path: bip39_recovery-macos.zip

  # ------------------- 创建 GitHub Release -------------------
  create-release:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: |
            ## BIP39 恢复工具 - 跨平台发布版
            本次发布包含了 Windows、Linux 和 macOS 的可执行文件。
            `english.txt` 词库文件已内嵌到每个应用中，无需额外文件。
          generate_release_notes: true
          files: |
            artifacts/bip39-recovery-windows/bip39_recovery-windows.exe
            artifacts/bip39-recovery-linux/bip39_recovery-linux
            artifacts/bip39-recovery-macos/bip39_recovery-macos.zip
